import { randomUUID } from 'crypto'
import { Hotel } from 'domain/entities/hotel/hotel'

export const mockHotels: Hotel[] = [
  {
    _id: randomUUID(),
    chain_name: 'No chain',
    hotel_name: 'Haihua Hotel Hangzhou',
    addressline1: 'No. 298, Qing Chun Road',
    addressline2: '',
    zipcode: '310006',
    city: 'Hangzhou',
    state: 'Zhejiang',
    country: 'China',
    countryisocode: 'CN',
    star_rating: 4,
  },
  {
    _id: randomUUID(),
    chain_name: 'Samed Resorts Group',
    hotel_name: 'Sai Kaew Beach Resort',
    addressline1: '8/1 Moo 4 Tumbon Phe Muang',
    addressline2: '',
    zipcode: '21160',
    city: 'Koh Samet',
    state: 'Rayong',
    country: 'Thailand',
    countryisocode: 'TH',
    star_rating: 4,
  },
  {
    _id: randomUUID(),
    chain_name: 'No chain',
    hotel_name: 'Marine Hotel',
    addressline1: 'Sutton Cross',
    addressline2: '',
    zipcode: 'D13',
    city: 'Dublin',
    state: '',
    country: 'Ireland',
    countryisocode: 'IE',
    star_rating: 3,
  },
  {
    _id: randomUUID(),
    chain_name: 'Melia Hotels International',
    hotel_name: 'TRYP Malaga Alameda Hotel',
    addressline1: 'Avenida de la Aurora CC.Larios Centro S/N',
    addressline2: '',
    zipcode: '29002',
    city: 'Malaga',
    state: 'Andalusia',
    country: 'Spain',
    countryisocode: 'ES',
    star_rating: 4,
  },
  {
    _id: randomUUID(),
    chain_name: 'NH Hotels',
    hotel_name: 'NH Iquique Hotel',
    addressline1: 'Av Costanera 3939',
    addressline2: '',
    zipcode: '1111500',
    city: 'Iquique',
    state: 'Tarapacá',
    country: 'Chile',
    countryisocode: 'CL',
    star_rating: 4,
  },
]
